version: '3.6'
services:
  postgres:
    image: docker.io/library/postgres:12
    ports:
      - 15432:5432
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: devenvpgpassword
  graphql-engine:
    image: docker.io/hasura/graphql-engine:v2.16.1
    ports:
      - 18080:8080
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:devenvpgpassword@postgres:5432/hasura
      PG_DATABASE_URL: postgres://postgres:devenvpgpassword@postgres:5432/vaalidata
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data:

